---
# handlers file for ansible-newrelic

- name: start newrelic
  service:
    name: newrelic-infra
    state: started

- name: stop newrelic
  service:
    name: newrelic-infra
    state: stopped

- name: restart newrelic
  service:
    name: newrelic-infra
    state: restarted
